name: Generate profile animations

on:
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generateAll:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Generate Breek Animation
        uses: cherninlab/breek@v1.0.5
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-breek.svg
          svg_dark_out_path: dist/github-contribution-grid-breek-dark.svg

      - name: Generate name Animation
        uses: ./
        with:
          login: Zxilly
          output: 'animation'
          type: webp

      - name: Push all animations to output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
